Fix compilation error: change houseResponseFound from let to var
Changed houseResponseFound from a let constant to a var variable
since we need to reassign it when checking for alternative response
patterns in testMessageBubbleDisplay.